//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8825
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translations.i18n.modules.site.taskmanager.index {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translations.i18n.modules.site.taskmanager.index.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [new].
        /// </summary>
        public static string button_new {
            get {
                return ResourceManager.GetString("button_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [yes].
        /// </summary>
        public static string confirmdeletetask_modal_button_yes {
            get {
                return ResourceManager.GetString("confirmdeletetask_modal_button_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [are you sure?].
        /// </summary>
        public static string confirmdeletetask_modal_message {
            get {
                return ResourceManager.GetString("confirmdeletetask_modal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [confirm delete task].
        /// </summary>
        public static string confirmdeletetask_modal_title {
            get {
                return ResourceManager.GetString("confirmdeletetask_modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [create].
        /// </summary>
        public static string dialogboxtask_modal_button_create {
            get {
                return ResourceManager.GetString("dialogboxtask_modal_button_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [update].
        /// </summary>
        public static string dialogboxtask_modal_button_update {
            get {
                return ResourceManager.GetString("dialogboxtask_modal_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [edit task].
        /// </summary>
        public static string dialogboxtask_modal_title {
            get {
                return ResourceManager.GetString("dialogboxtask_modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [cancel].
        /// </summary>
        public static string modal_button_cancel {
            get {
                return ResourceManager.GetString("modal_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [tasks].
        /// </summary>
        public static string name_table {
            get {
                return ResourceManager.GetString("name_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [assignee].
        /// </summary>
        public static string th_assignee {
            get {
                return ResourceManager.GetString("th_assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [description].
        /// </summary>
        public static string th_description {
            get {
                return ResourceManager.GetString("th_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [id].
        /// </summary>
        public static string th_id {
            get {
                return ResourceManager.GetString("th_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [name].
        /// </summary>
        public static string th_name {
            get {
                return ResourceManager.GetString("th_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [reporter].
        /// </summary>
        public static string th_reporter {
            get {
                return ResourceManager.GetString("th_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [when completed].
        /// </summary>
        public static string th_whencompleted {
            get {
                return ResourceManager.GetString("th_whencompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [when created].
        /// </summary>
        public static string th_whencreated {
            get {
                return ResourceManager.GetString("th_whencreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [test work for worknest. task manager].
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
