// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Logs.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_7c2229cb57c14bf3bfb07099cc32c239 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_7c2229cb57c14bf3bfb07099cc32c239));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140517394_vasiliy.stan_7c2229cb57c14bf3bfb07099cc32c239"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
