#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\TaskManager\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\TaskManager\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\TaskManager\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\TaskManager\Index.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/TaskManager/Index.cshtml")]
    public partial class _TaskManager_Index_cshtml : System.Web.Mvc.WebViewPage<Modules.Site.TaskManager.TaskManagerModel>
    {
        public _TaskManager_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\TaskManager\Index.cshtml"
  
    Layout = "~/TaskManager.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\TaskManager\Index.cshtml"
Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("bodyscripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(document).ready(function() {\r\n            $(\'#dataTable" +
"s-tasks\').DataTable({\r\n                responsive: true\r\n            });\r\n      " +
"      $(\'#task-whencreated\').datepicker();\r\n            $(\'#task-whencompleted\')" +
".datepicker();\r\n        });\r\n    </script>\r\n    <script>\r\n        $(document).re" +
"ady(function() {\r\n\r\n            function selectSetFirstElement(id) {\r\n          " +
"      var firstOptionElement = $(id + \' option\')[0];\r\n                var valueF" +
"irstOptionElement = $(firstOptionElement).val();\r\n                $(id).val(valu" +
"eFirstOptionElement);\r\n            }\r\n\r\n            $(\'#dataTables-tasks\').on(\'c" +
"lick\',\r\n                \'.btn-edit-task\',\r\n                function (e) {\r\n     " +
"               var taskId = $(e.currentTarget).data(\'task-id\');\r\n               " +
"     localStorage.setItem(\"update-task-id\", taskId);\r\n                    $.Site" +
".Libraries.Common.Preloader.Show();\r\n                    $.Site.Libraries.WebApi" +
".Common.ExecuteAction({\r\n                        uri: $(\"#webapi-taskmanager-sel" +
"ect\").attr(\"href\"),\r\n                        data:\r\n                        {\r\n " +
"                           Task:\r\n                            {\r\n               " +
"                 Id: localStorage.getItem(\"update-task-id\")\r\n                   " +
"         }\r\n                        },\r\n                        onSuccess: funct" +
"ion (response) {\r\n                            $(\'#task-name\').val(response.Task." +
"Name);\r\n                            $(\'#task-description\').val(response.Task.Des" +
"cription);\r\n                            $(\'#task-whencreated\').val(response.Task" +
".JsWhenCreated),\r\n                            $(\'#task-whencompleted\').val(respo" +
"nse.Task.JsWhenCompleted),\r\n                            $(\'#task-reporter\').val(" +
"response.Task.Reporter);\r\n                            $(\'#task-assignee\').val(re" +
"sponse.Task.Assignee);\r\n                            $(\'#btn-task-create\').addCla" +
"ss(\'hidden\');\r\n                            $(\'#btn-task-update\').removeClass(\'hi" +
"dden\');\r\n                            $(\'#DialogBoxTask\').modal(\'show\');\r\n       " +
"                 },\r\n                        onException: function (exception) {" +
" console.log(exception); },\r\n                        onExceptionFail: function (" +
"exception) { console.log(exception); },\r\n                        onAfterAction: " +
"function () { $.Site.Libraries.Common.Preloader.Hide(); }\r\n                    }" +
");\r\n                });\r\n\r\n            $(\'#dataTables-tasks\').on(\'click\',\r\n     " +
"           \'.btn-delete-task\',\r\n                function(e) {\r\n                 " +
"   var taskId = $(e.currentTarget).data(\'task-id\');\r\n                    localSt" +
"orage.setItem(\"delete-task-id\", taskId);\r\n                });\r\n\r\n            $(\'" +
"#btn-task-create\').on(\'click\',\r\n                function(e) {\r\n                 " +
"   $.Site.Libraries.Common.Preloader.Show();\r\n                    $.Site.Librari" +
"es.WebApi.Common.ExecuteAction({\r\n                        uri: $(\"#webapi-taskma" +
"nager-create\").attr(\"href\"),\r\n                        data:\r\n                   " +
"     {\r\n                            Task:\r\n                            {\r\n      " +
"                          Name: $(\'#task-name\').val(),\r\n                        " +
"        Description: $(\'#task-description\').val(),\r\n                            " +
"    WhenCreated: $(\'#task-whencreated\').val(),\r\n                                " +
"WhenCompleted: $(\'#task-whencompleted\').val(),\r\n                                " +
"Reporter: $(\'#task-reporter option:selected\').val(),\r\n                          " +
"      Assignee: $(\'#task-assignee option:selected\').val()\r\n                     " +
"       }\r\n                        },\r\n                        onAfterAction: fun" +
"ction() { window.location.reload(false); }\r\n                    });\r\n           " +
"     });\r\n\r\n            $(\'#btn-task-update\').on(\'click\',\r\n                funct" +
"ion(e) {\r\n                    $.Site.Libraries.Common.Preloader.Show();\r\n       " +
"             $.Site.Libraries.WebApi.Common.ExecuteAction({\r\n                   " +
"     uri: $(\"#webapi-taskmanager-update\").attr(\"href\"),\r\n                       " +
" data:\r\n                        {\r\n                            Task:\r\n          " +
"                  {\r\n                                Id: localStorage.getItem(\"u" +
"pdate-task-id\"),\r\n                                Name: $(\'#task-name\').val(),\r\n" +
"                                Description: $(\'#task-description\').val(),\r\n    " +
"                            WhenCreated: $(\'#task-whencreated\').val(),\r\n        " +
"                        WhenCompleted: $(\'#task-whencompleted\').val(),\r\n        " +
"                        Reporter: $(\'#task-reporter option:selected\').val(),\r\n  " +
"                              Assignee: $(\'#task-assignee option:selected\').val(" +
")\r\n                            }\r\n                        },\r\n                  " +
"      onAfterAction: function() { window.location.reload(false); }\r\n            " +
"        });\r\n                });\r\n\r\n            $(\'#confirmDeleteTask\').on(\'clic" +
"k\',\r\n                \'.btn-yes\',\r\n                function(e) {\r\n               " +
"     $.Site.Libraries.Common.Preloader.Show();\r\n                    $.Site.Libra" +
"ries.WebApi.Common.ExecuteAction({\r\n                        uri: $(\"#webapi-task" +
"manager-delete\").attr(\"href\"),\r\n                        data:\r\n                 " +
"       {\r\n                            Task:\r\n                            {\r\n    " +
"                            Id: localStorage.getItem(\"delete-task-id\")\r\n        " +
"                    }\r\n                        },\r\n                        onAft" +
"erAction: function() { window.location.reload(false); }\r\n                    });" +
"\r\n                });\r\n\r\n            $(\'#btn-new-task\').on(\'click\',\r\n           " +
"     function(e) {\r\n                    $(\'#task-name\').val(\'\');\r\n              " +
"      $(\'#task-description\').val(\'\');\r\n                    $(\'#task-whencreated\'" +
").datepicker(\'setDate\', \'today\');\r\n                    $(\'#task-whencompleted\')." +
"datepicker(\'setDate\', \'today\');\r\n                    selectSetFirstElement(\'#tas" +
"k-reporter\');\r\n                    selectSetFirstElement(\'#task-assignee\');\r\n   " +
"                 $(\'#btn-task-update\').addClass(\'hidden\');\r\n                    " +
"$(\'#btn-task-create\').removeClass(\'hidden\');\r\n                    $(\'#DialogBoxT" +
"ask\').modal(\'show\');\r\n                });\r\n        });\r\n\r\n    </script>\r\n");

});

WriteLiteral("\r\n<a");

WriteLiteral(" id=\"webapi-taskmanager-select\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6698), Tuple.Create("\"", 6733)
, Tuple.Create(Tuple.Create("", 6705), Tuple.Create<System.Object, System.Int32>(Href("~/api/taskmanager/selecttask")
, 6705), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"webapi-taskmanager-create\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6789), Tuple.Create("\"", 6824)
, Tuple.Create(Tuple.Create("", 6796), Tuple.Create<System.Object, System.Int32>(Href("~/api/taskmanager/createtask")
, 6796), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"webapi-taskmanager-update\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6880), Tuple.Create("\"", 6915)
, Tuple.Create(Tuple.Create("", 6887), Tuple.Create<System.Object, System.Int32>(Href("~/api/taskmanager/updatetask")
, 6887), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"webapi-taskmanager-delete\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6971), Tuple.Create("\"", 7006)
, Tuple.Create(Tuple.Create("", 6978), Tuple.Create<System.Object, System.Int32>(Href("~/api/taskmanager/deletetask")
, 6978), false)
);

WriteLiteral("></a>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    \r\n    <div");

WriteLiteral(" id=\"confirmDeleteTask\"");

WriteLiteral(" class=\"col-md-offset-2 col-md-8 modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n                    </button>                    \r\n                   " +
" <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 165 "..\..\TaskManager\Index.cshtml"
                                       Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "confirmdeletetask_modal_title"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body text-align-center\"");

WriteLiteral(">");

            
            #line 167 "..\..\TaskManager\Index.cshtml"
                                                     Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "confirmdeletetask_modal_message"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-primary btn-yes\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 169 "..\..\TaskManager\Index.cshtml"
                                                                                          Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "confirmdeletetask_modal_button_yes"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">");

            
            #line 170 "..\..\TaskManager\Index.cshtml"
                                                                                                      Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "modal_button_cancel"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>    \r" +
"\n    \r\n    <div");

WriteLiteral(" id=\"DialogBoxTask\"");

WriteLiteral(" class=\"col-md-offset-2 col-md-8 modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n                    </button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 183 "..\..\TaskManager\Index.cshtml"
                                       Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "dialogboxtask_modal_title"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-offset-1 col-md-10\"");

WriteLiteral(">\r\n                            <form");

WriteLiteral(" role=\"form\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-name\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 191 "..\..\TaskManager\Index.cshtml"
                                                                                Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_name"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"task-name\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("/>\r\n                                    </div>\r\n                                <" +
"/div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-description\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 199 "..\..\TaskManager\Index.cshtml"
                                                                                       Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_description"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"task-description\"");

WriteLiteral("></textarea>\r\n                                    </div>\r\n                       " +
"         </div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-whencreated\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 207 "..\..\TaskManager\Index.cshtml"
                                                                                       Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_whencreated"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"task-whencreated\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-whencompleted\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 215 "..\..\TaskManager\Index.cshtml"
                                                                                         Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_whencompleted"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"task-whencompleted\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-reporter\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 223 "..\..\TaskManager\Index.cshtml"
                                                                                    Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_reporter"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" id=\"task-reporter\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n");

            
            #line 227 "..\..\TaskManager\Index.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 227 "..\..\TaskManager\Index.cshtml"
                                             foreach (var user in Model.Users)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 12329), Tuple.Create("\"", 12342)
            
            #line 229 "..\..\TaskManager\Index.cshtml"
, Tuple.Create(Tuple.Create("", 12337), Tuple.Create<System.Object, System.Int32>(user
            
            #line default
            #line hidden
, 12337), false)
);

WriteLiteral(">");

            
            #line 229 "..\..\TaskManager\Index.cshtml"
                                                                 Write(user);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 230 "..\..\TaskManager\Index.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </select>\r\n                              " +
"      </div>\r\n                                </div>\r\n                          " +
"      <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-4 text-align-right vertical-align-middle\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"task-assignee\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 236 "..\..\TaskManager\Index.cshtml"
                                                                                    Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_assignee"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" id=\"task-assignee\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n");

            
            #line 240 "..\..\TaskManager\Index.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 240 "..\..\TaskManager\Index.cshtml"
                                             foreach (var user in Model.Users)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 13251), Tuple.Create("\"", 13264)
            
            #line 242 "..\..\TaskManager\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13259), Tuple.Create<System.Object, System.Int32>(user
            
            #line default
            #line hidden
, 13259), false)
);

WriteLiteral(">");

            
            #line 242 "..\..\TaskManager\Index.cshtml"
                                                                 Write(user);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 243 "..\..\TaskManager\Index.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral(@"                                        </select>
                                    </div>
                                </div>
                            </form>                            
                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-offset-1 col-md-10\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" id=\"btn-task-create\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 254 "..\..\TaskManager\Index.cshtml"
                                                                                                               Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "dialogboxtask_modal_button_create"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                            <button");

WriteLiteral(" id=\"btn-task-update\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 255 "..\..\TaskManager\Index.cshtml"
                                                                                                               Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "dialogboxtask_modal_button_update"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                            <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">");

            
            #line 256 "..\..\TaskManager\Index.cshtml"
                                                                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "modal_button_cancel"));

            
            #line default
            #line hidden
WriteLiteral("</a>                            \r\n                        </div>\r\n               " +
"     </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </d" +
"iv>      \r\n    \r\n    \r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-9 text-align-center h4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 271 "..\..\TaskManager\Index.cshtml"
                       Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "name_table"));

            
            #line default
            #line hidden
WriteLiteral("                            \r\n                        </div>                     " +
"   \r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-offset-7 col-md-5\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" id=\"btn-new-task\"");

WriteLiteral(" class=\"btn btn-primary col-md-12 text-align-left\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-fw fa-plus\"");

WriteLiteral(">");

            
            #line 277 "..\..\TaskManager\Index.cshtml"
                                                               Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "button_new"));

            
            #line default
            #line hidden
WriteLiteral(@"</i>
                                    </a>                                                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(" id=\"dataTables-tasks\"");

WriteLiteral(">\r\n                        <thead>\r\n                        <tr>\r\n               " +
"             <th");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 289 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_id"));

            
            #line default
            #line hidden
WriteLiteral("</th>                            \r\n                            <th");

WriteLiteral(" class=\"col-md-3 text-align-center\"");

WriteLiteral(">");

            
            #line 290 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_name"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 291 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_whencreated"));

            
            #line default
            #line hidden
WriteLiteral("</th>  \r\n                            <th");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 292 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_whencompleted"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th");

WriteLiteral(" class=\"col-md-2 text-align-center\"");

WriteLiteral(">");

            
            #line 293 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_reporter"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th");

WriteLiteral(" class=\"col-md-2 text-align-center\"");

WriteLiteral(">");

            
            #line 294 "..\..\TaskManager\Index.cshtml"
                                                              Write(I18NEngine.GetMvcHtmlString("modules.site.taskmanager.index", "th_assignee"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral("></th>\r\n                        </tr>\r\n                        </thead>\r\n        " +
"                <tbody>\r\n");

            
            #line 299 "..\..\TaskManager\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 299 "..\..\TaskManager\Index.cshtml"
                               var index = 0;
            
            #line default
            #line hidden
WriteLiteral("    \r\n");

            
            #line 300 "..\..\TaskManager\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 300 "..\..\TaskManager\Index.cshtml"
                             foreach (var task in Model.Tasks)
                            {
                                index++;
                                var trClass = index % 2 == 1 ? "even" : "odd";

            
            #line default
            #line hidden
WriteLiteral("                                <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 17411), Tuple.Create("\"", 17434)
            
            #line 304 "..\..\TaskManager\Index.cshtml"
, Tuple.Create(Tuple.Create("", 17419), Tuple.Create<System.Object, System.Int32>(trClass
            
            #line default
            #line hidden
, 17419), false)
, Tuple.Create(Tuple.Create(" ", 17427), Tuple.Create("gradeA", 17428), true)
);

WriteLiteral(">\r\n                                    <td");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 305 "..\..\TaskManager\Index.cshtml"
                                                                      Write(index);

            
            #line default
            #line hidden
WriteLiteral("</td>                            \r\n                                    <td");

WriteLiteral(" class=\"col-md-3 text-align-center\"");

WriteLiteral(">");

            
            #line 306 "..\..\TaskManager\Index.cshtml"
                                                                      Write(task.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 307 "..\..\TaskManager\Index.cshtml"
                                                                      Write(task.WhenCreated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</td>  \r\n                                    <td");

WriteLiteral(" class=\"col-md-1 text-align-center\"");

WriteLiteral(">");

            
            #line 308 "..\..\TaskManager\Index.cshtml"
                                                                      Write(task.WhenCompleted.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2 text-align-center\"");

WriteLiteral(">");

            
            #line 309 "..\..\TaskManager\Index.cshtml"
                                                                      Write(task.Reporter);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2 text-align-center\"");

WriteLiteral(">");

            
            #line 310 "..\..\TaskManager\Index.cshtml"
                                                                      Write(task.Assignee);

            
            #line default
            #line hidden
WriteLiteral("</td>                                    \r\n\r\n                                    " +
"<td");

WriteLiteral(" class=\"col-md-6 text-align-center\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" class=\"blue btn-edit-task\"");

WriteLiteral(" data-task-id=\"");

            
            #line 313 "..\..\TaskManager\Index.cshtml"
                                                                               Write(task.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"fa fa-fw fa-pencil\"");

WriteLiteral("></i>\r\n                                        </a>\r\n                            " +
"            <a");

WriteLiteral(" class=\"red btn-delete-task\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#confirmDeleteTask\"");

WriteLiteral(" data-task-id=\"");

            
            #line 316 "..\..\TaskManager\Index.cshtml"
                                                                                                                                     Write(task.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"fa fa-fw fa-trash-o\"");

WriteLiteral("></i>\r\n                                        </a>\r\n                            " +
"        </td>\r\n                                </tr>                            " +
"\r\n");

            
            #line 321 "..\..\TaskManager\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral(@"                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>

</div>");

        }
    }
}
#pragma warning restore 1591
