#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\DetailsPages.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\DetailsPages.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\DetailsPages.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/DetailsPages.cshtml")]
    public partial class _DetailsPages_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _DetailsPages_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n        <title>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\DetailsPages.cshtml"
       Write(RenderSection("pagetitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </title>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\DetailsPages.cshtml"
   Write(Styles.Render("~/Libraries/Components/Preloader/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 470), Tuple.Create("\"", 562)
, Tuple.Create(Tuple.Create("", 477), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min" +
".css")
, 477), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\DetailsPages.cshtml"
   Write(Styles.Render("~/Libraries/Components/MultiSelect/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 662), Tuple.Create("\"", 750)
, Tuple.Create(Tuple.Create("", 669), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css" +
"")
, 669), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 784), Tuple.Create("\"", 861)
, Tuple.Create(Tuple.Create("", 791), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css")
, 791), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 895), Tuple.Create("\"", 993)
, Tuple.Create(Tuple.Create("", 902), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/font-awesome/css/font-aweso" +
"me.min.css")
, 902), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\DetailsPages.cshtml"
   Write(Styles.Render("~/Libraries/Common/css"));

            
            #line default
            #line hidden
WriteLiteral("       \r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\DetailsPages.cshtml"
   Write(RenderSection("stylesheet", false));

            
            #line default
            #line hidden
WriteLiteral("        \r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1165), Tuple.Create("\"", 1245)
, Tuple.Create(Tuple.Create("", 1171), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js")
, 1171), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\DetailsPages.cshtml"
   Write(Scripts.Render("~/Libraries/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\DetailsPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\DetailsPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\DetailsPages.cshtml"
   Write(RenderSection("headscripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>    \r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\DetailsPages.cshtml"
               Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.home", "navbar_brand_link"), "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 37 "..\..\DetailsPages.cshtml"
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\DetailsPages.cshtml"
                 if (User.Identity.IsAuthenticated)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"navbar-header navbar-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\DetailsPages.cshtml"
                   Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.home", "exit_link"), "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>                    \r\n");

            
            #line 42 "..\..\DetailsPages.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    \r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\DetailsPages.cshtml"
   Write(RenderPage("~/Sidebar.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\DetailsPages.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2456), Tuple.Create("\"", 2545)
, Tuple.Create(Tuple.Create("", 2462), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min." +
"js")
, 2462), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2573), Tuple.Create("\"", 2659)
, Tuple.Create(Tuple.Create("", 2579), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js")
, 2579), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2687), Tuple.Create("\"", 2761)
, Tuple.Create(Tuple.Create("", 2693), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js")
, 2693), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 53 "..\..\DetailsPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/MultiSelect/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\DetailsPages.cshtml"
   Write(RenderSection("bodyscripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 55 "..\..\DetailsPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/Preloader/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
