#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Login.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Login.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Login.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Login.cshtml")]
    public partial class _Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n        <title>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Login.cshtml"
       Write(RenderSection("pagetitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </title>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Login.cshtml"
   Write(Styles.Render("~/Libraries/Components/Preloader/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Login.cshtml"
   Write(Styles.Render("~/Themes/startbootstrap-sb-admin-2/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Login.cshtml"
   Write(Styles.Render("~/Libraries/Common/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Login.cshtml"
   Write(RenderSection("stylesheet", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Login.cshtml"
   Write(RenderSection("headscripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>    \r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Login.cshtml"
               Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.common", "navbar_brand_link"), "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Login.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Login.cshtml"
   Write(Scripts.Render("~/Themes/startbootstrap-sb-admin-2/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Login.cshtml"
   Write(Scripts.Render("~/Libraries/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Login.cshtml"
   Write(RenderSection("bodyscripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Login.cshtml"
   Write(Scripts.Render("~/Libraries/Components/Preloader/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
