#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\TaskManager.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\TaskManager.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\TaskManager.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/TaskManager.cshtml")]
    public partial class _TaskManager_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _TaskManager_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n        <title>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\TaskManager.cshtml"
       Write(RenderSection("pagetitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 406), Tuple.Create("\"", 491)
, Tuple.Create(Tuple.Create("", 413), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/jquery/jquery-ui.min.css")
, 413), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 525), Tuple.Create("\"", 617)
, Tuple.Create(Tuple.Create("", 532), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min" +
".css")
, 532), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 651), Tuple.Create("\"", 739)
, Tuple.Create(Tuple.Create("", 658), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css" +
"")
, 658), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 773), Tuple.Create("\"", 877)
, Tuple.Create(Tuple.Create("", 780), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTabl" +
"es.bootstrap.css")
, 780), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 911), Tuple.Create("\"", 1019)
, Tuple.Create(Tuple.Create("", 918), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-responsive/dataT" +
"ables.responsive.css")
, 918), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1053), Tuple.Create("\"", 1130)
, Tuple.Create(Tuple.Create("", 1060), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css")
, 1060), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1164), Tuple.Create("\"", 1262)
, Tuple.Create(Tuple.Create("", 1171), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/font-awesome/css/font-aweso" +
"me.min.css")
, 1171), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src=""https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js""></script>
            <script src=""https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js""></script>
        <![endif]-->
");

WriteLiteral("        ");

            
            #line 27 "..\..\TaskManager.cshtml"
   Write(Styles.Render("~/Libraries/Common/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\TaskManager.cshtml"
   Write(Styles.Render("~/Libraries/Components/Preloader/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1856), Tuple.Create("\"", 1936)
, Tuple.Create(Tuple.Create("", 1862), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js")
, 1862), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1964), Tuple.Create("\"", 2047)
, Tuple.Create(Tuple.Create("", 1970), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/jquery/jquery-ui.min.js")
, 1970), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\TaskManager.cshtml"
   Write(Scripts.Render("~/Libraries/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\TaskManager.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\TaskManager.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>    \r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\TaskManager.cshtml"
               Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.common", "navbar_brand_link"), "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 45 "..\..\TaskManager.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\TaskManager.cshtml"
                 if (User.Identity.IsAuthenticated)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"navbar-header navbar-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 48 "..\..\TaskManager.cshtml"
                   Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.common", "exit_link"), "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>                    \r\n");

            
            #line 50 "..\..\TaskManager.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n\r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\TaskManager.cshtml"
   Write(RenderPage("~/Sidebar.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\TaskManager.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3214), Tuple.Create("\"", 3303)
, Tuple.Create(Tuple.Create("", 3220), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min." +
"js")
, 3220), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3331), Tuple.Create("\"", 3417)
, Tuple.Create(Tuple.Create("", 3337), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js")
, 3337), false)
);

WriteLiteral("></script>\r\n\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3447), Tuple.Create("\"", 3545)
, Tuple.Create(Tuple.Create("", 3453), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables/js/jquery.dataTa" +
"bles.min.js")
, 3453), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3573), Tuple.Create("\"", 3679)
, Tuple.Create(Tuple.Create("", 3579), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTabl" +
"es.bootstrap.min.js")
, 3579), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3707), Tuple.Create("\"", 3813)
, Tuple.Create(Tuple.Create("", 3713), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-responsive/dataT" +
"ables.responsive.js")
, 3713), false)
);

WriteLiteral("></script>\r\n\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3843), Tuple.Create("\"", 3917)
, Tuple.Create(Tuple.Create("", 3849), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js")
, 3849), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 65 "..\..\TaskManager.cshtml"
   Write(RenderSection("bodyscripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\TaskManager.cshtml"
   Write(Scripts.Render("~/Libraries/Components/Preloader/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
