#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Home\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Home\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Home\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Home\Index.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Home/Index.cshtml")]
    public partial class _Home_Index_cshtml : System.Web.Mvc.WebViewPage<Modules.Site.Home.HomeModel>
    {
        public _Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Home\Index.cshtml"
  
    Layout = "~/Home.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Home\Index.cshtml"
Write(I18NEngine.GetMvcHtmlString("modules.site.home.index", "title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <h1>");

            
            #line 19 "..\..\Home\Index.cshtml"
           Write(I18NEngine.GetMvcHtmlString("modules.site.home.index", "header1"));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            <br />\r\n            <h3>");

            
            #line 21 "..\..\Home\Index.cshtml"
           Write(I18NEngine.GetMvcHtmlString("modules.site.home.index", "header3"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n            <ul>\r\n");

            
            #line 23 "..\..\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Home\Index.cshtml"
                 foreach (var module in Model.Modules)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>");

            
            #line 25 "..\..\Home\Index.cshtml"
                   Write(module);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 26 "..\..\Home\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
